<a href="https://colab.research.google.com/github/ErangaOttachchige/Amazon-Clone-JS/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

Torch random tensors: https://docs.pytorch.org/docs/stable/generated/torch.rand.html


In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9654, 0.5353, 0.2316, 0.9484],
        [0.1879, 0.1503, 0.9724, 0.3590],
        [0.8731, 0.2693, 0.5524, 0.7991]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(size=(3, 3))

tensor([[0.5482, 0.4985, 0.0630],
        [0.8406, 0.8142, 0.5873],
        [0.6733, 0.3808, 0.0854]])

In [22]:
torch.rand(3,3)

tensor([[0.4616, 0.7074, 0.0967],
        [0.2711, 0.6614, 0.1083],
        [0.8494, 0.5324, 0.5955]])

## Zeros and ones


In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype # .dtype --> default data type

torch.float32

In [27]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [28]:
# Use torch.range() and get deprecated message, use torch.arange() instead
torch.range(0,10)

/tmp/ipython-input-1100087402.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
torch.__version__

'2.8.0+cu126'

In [30]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ranges = torch.arange(start=0, end=1000, step=77)
ranges

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

# Creating tensors like


In [32]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

:## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with Pytorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # by default this is going to be "cpu" (e.g. "cpu", "cuda"  --> this is a GPU)
                               # what device is your tensor on
                               requires_grad=False) # if you want to track the gradients of a tensor when it goes through certain numerical calculations
                               # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
# Default data type in pytorch even if it is specified as "None" is going to come out as "torch.float32"
float_32_tensor.dtype

torch.float32

In [35]:
# how we change the tensor datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor.dtype

torch.float16

In [38]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [39]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [41]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3919, 0.7491, 0.0538, 0.9828],
        [0.4542, 0.5971, 0.7049, 0.9215],
        [0.0918, 0.9449, 0.8218, 0.2721]])

In [42]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [43]:
# some_tensor.size(), is a function, not an attribute
some_tensor.size()

torch.Size([3, 4])

In [44]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3919, 0.7491, 0.0538, 0.9828],
        [0.4542, 0.5971, 0.7049, 0.9215],
        [0.0918, 0.9449, 0.8218, 0.2721]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix Multiplication

In [45]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [47]:
tensor

tensor([1, 2, 3])

In [48]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [49]:
# Try out in_built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix Multiplication

Two main ways of performing multiplication in Neural Network & Deep Learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match :
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions** :
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [51]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.9193, 0.7134, 0.8889],
        [1.2705, 0.9550, 1.2173],
        [0.9431, 0.7913, 0.9335]])

In [52]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
tensor @ tensor

tensor(14)

In [55]:
tensor

tensor([1, 2, 3])

In [56]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [57]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.51 ms, sys: 0 ns, total: 1.51 ms
Wall time: 4.37 ms


In [58]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 130 µs, sys: 20 µs, total: 150 µs
Wall time: 174 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [59]:
# Shape for matrix mutiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)  # torch.mm() is the same as torch.matmul() (it is an alias for writing less code)
# torch.matmul(tensor_A, tensor_B) --> this cause an error because
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [60]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **torch.transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [61]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [62]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [63]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [64]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [65]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [67]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [68]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [69]:
# Find the mean - note: the torch.mean() function requires a tensor of a floating point or complex datatype to work

# Input dtype must be either a floating point or complex dtype.

torch.mean(x.type(torch.float32)), x.type(torch.float64).mean()

(tensor(46.), tensor(46., dtype=torch.float64))

In [70]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max of tensors

In [71]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Find the position in tensor that has the minimum value with .argmin() -> returns the index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [73]:
x[0]

tensor(1)

In [74]:
# Find the position in tensor that has the maximum value with .argmax()
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [75]:
x[9]

tensor(91)

In [76]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Returns a view of the input with dimensions permuted (swapped) in a certain way



###1. Reshape

* **What it does**: Changes the shape of a tensor to the size you want, without changing the data.

* **Special use**: Rearranging data into a structure useful for a layer/operation.

* **Important**: The number of elements must stay the same.

In [77]:
import torch
x = torch.arange(1, 7)  # tensor([1, 2, 3, 4, 5, 6])
print(x.shape)          # torch.Size([6])

y = x.reshape(2, 3)
print(y)
# tensor([[1, 2, 3],
#         [4, 5, 6]])


torch.Size([6])
tensor([[1, 2, 3],
        [4, 5, 6]])


✅ Use when you need to change shape for feeding into a neural network.
Example: flattening images into 1D vectors, or splitting back into matrices.

##2. View

* **What it does**: Similar to `reshape`, but it **keeps the same memory layout** (doesn’t create a copy if possible).

* **Special use**: Very efficient for reshaping when the tensor is contiguous in memory.

* **Key point**: You may need `.contiguous()` before calling `.view()` sometimes.

In [78]:
x = torch.arange(1, 7)
y = x.view(2, 3)
print(y)
# tensor([[1, 2, 3],
#         [4, 5, 6]])


tensor([[1, 2, 3],
        [4, 5, 6]])


✅ Use `view` if you only want a **different view** of the same data without making copies.
Example: flattening for a fully connected layer inside a model.

## 3. Stack

**What it does**: Joins multiple tensors together along a **new dimension**.

**Special use**: Making a batch from separate examples.

In [79]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = torch.stack([a, b])
print(c)
# tensor([[1, 2],
#         [3, 4]])


tensor([[1, 2],
        [3, 4]])


If you want them side by side or vertical, change `dim`:

In [80]:
c = torch.stack([a, b], dim=1)
print(c)
# tensor([[1, 3],
#         [2, 4]])

tensor([[1, 3],
        [2, 4]])


✅ Use when you need to combine multiple tensors into a new axis (e.g., stacking multiple images into a batch).

## 4. Squeeze
* **What it does**: Removes dimensions of size 1.
* **Special use**: Gets rid of “dummy” dimensions added during processing.

In [81]:
x = torch.zeros(1, 3, 1, 5)
print(x.shape)  # torch.Size([1, 3, 1, 5])

y = x.squeeze()
print(y.shape)  # torch.Size([3, 5])

torch.Size([1, 3, 1, 5])
torch.Size([3, 5])


In [82]:
y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

✅ Use to clean up shapes, e.g., turning `[1, 28, 28]` into `[28, 28]` for an image.

## 5. Unsqueeze

* **What it does**: Adds a dimension of size 1 at a chosen position.

* **Special use**: Matching shapes for operations (broadcasting, batching).

In [83]:
x = torch.tensor([1, 2, 3])
print(x)
print(x.shape)  # torch.Size([3])

y = x.unsqueeze(0)
print(y)
print(y.shape)  # torch.Size([1, 3])

z = x.unsqueeze(1)
print(z.shape)  # torch.Size([3, 1])

z = x.unsqueeze(1)
print(z)
print(z.shape)  # torch.Size([3, 1])

tensor([1, 2, 3])
torch.Size([3])
tensor([[1, 2, 3]])
torch.Size([1, 3])
torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


✅ Use when you need an extra dimension, e.g., turning a single image `[28,28]` into a batch `[1,28,28]`.

## 6. Permute

* **What it does**: Reorders (swaps) the dimensions of a tensor.

* **Special use**: Changing format between different libraries (e.g., PyTorch expects channel-first `[C,H,W]` while some libraries use `[H,W,C]`).

In [84]:
x = torch.randn(3, 64, 64)   # 3 color channels, 64x64 image
print(x.shape)               # torch.Size([3, 64, 64])

y = x.permute(1, 2, 0)       # move channels to last
print(y.shape)               # torch.Size([64, 64, 3])

torch.Size([3, 64, 64])
torch.Size([64, 64, 3])


✅ Use when working with images, NLP, or any data where axis order matters.

💡 Analogy: Imagine a Rubik’s Cube.

* Each `dim` is a direction (up–down, left–right, front–back).

* `dim=0` → stack along one direction.

* `dim=1` → stack along another direction.

📊 Analogy:

Imagine you have 2 lists: `[1, 2]` and `[3, 4]`.

`dim=0` = make them new rows in a table.

`dim=1` = zip them together into columns.

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Returns a view of the input with dimensions permuted (swapped) in a certain way



In [85]:
# Lets create a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [86]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

`view` is quite similar to `reshape`, but remember though that the `view` shares the same memory with the original input tensor.

So `z` is just a different view of `x`, so `z` shares the same memory as what `x` does.

In [88]:
# Changing z changes x (because a `view` of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

 ### Extra
 ### p[:, 0] = 5

That line is **NumPy array slicing and assignment.**

Let’s break it down:

Suppose `p` is a 2D NumPy array, like a matrix.

`:` means “all rows”.

`0` means “the first column” (Python uses 0-based indexing).

`p[:, 0]` → selects **all rows, but only the first column** → i.e., the entire first column of the array.

`= 5` → assigns the value `5` to every element in that column.


In [89]:
import numpy as np

p = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

p[:, 0] = 5   # set first column to 5
print(p)


[[5 2 3]
 [5 5 6]
 [5 8 9]]


👉 So `p[:, 0] = 5` means: “**replace all values in the first column of `p` with 5**”.

In [90]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

# Concatenates a sequence of tensors along a new dimension.
# All tensors need to be of the same size.

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [91]:
# torch.squeeze() - removes all single dimensions from a target tenosr
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Removes extra dimensions that is "1" from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [92]:
x_reshaped.shape

torch.Size([1, 9])

In [93]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [94]:
x_reshaped.squeeze().shape

torch.Size([9])

In [95]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [96]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

# torch.permute() is a PyTorch function used to rearrange the dimensions of a tensor.

x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dims) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print()
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

# Returns a view of the original tensor with its dimensions permuted according to a specified order.


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [97]:
x_original[0, 0, 0] = 728218

In [98]:
x_permuted[0, 0, 0], x_original[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [99]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [100]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [102]:
# Let's index on the most inner bracket (last dimension)
x[0][0][1], x[0, 2, 2]

(tensor(2), tensor(9))

In [103]:
# You can also use ":" to select "all" of a target dimension
x[:, 0] # get all of the 0th dimension and 0th index of 1st dim

tensor([[1, 2, 3]])

In [104]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [105]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [106]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [107]:
print(x)
print("\n")

# Index on x to return 9
print(x[0, 2, 2])

# Index x to return 3,6,9
print(x[:, :, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


tensor(9)
tensor([[3, 6, 9]])


#### PyTorch tensors & NumPy

Yes, NumPy is a fundamental package in Python, specifically designed for scientific computing. It provides a powerful N-dimensional array object (ndarray) and various tools for working with these arrays, including mathematical functions, linear algebra routines, Fourier transforms, and random number generation capabilities. It is widely used as a core component in many other scientific and data-related Python libraries.

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has funcionality to interact with NumPy.

* Data in NumPy -> want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [108]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from NumPy -> PyTorch, PyTorch reflects NumPy's default datatype of "float64" unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [109]:
# Change the value of array, what will this do to `tensor`?
array = array + 1 # adding 1 to every value in the array
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [110]:
# Tensor to NumPy array
tensor = torch.ones(7)  # PyTorch default datatype is "float32"
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:
numpy_tensor.dtype

dtype('float32')

In [112]:
# If change the "tensor", what happened to "numpy_tensor"?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

**Reproducibility just means:**

`If I run the same code today, tomorrow, or on another computer → I should get the same results.`

We set seeds to make sure experiments are **repeatable** (so you can debug or prove results).

**✅ In one line:**
A seed makes randomness predictable, and **reproducibility** means getting the same results every time you run your code.

In [113]:
import torch

torch.manual_seed(42)  # set the seed
print(torch.rand(3))   # random tensor
print(torch.rand(3))   # another random tensor

# Output (will always be the same every time you run it):
# If you change the seed, you’ll get different numbers.

tensor([0.8823, 0.9150, 0.3829])
tensor([0.9593, 0.3904, 0.6009])


# 🎯 Why do we care about seeds?

* **Reproducibility** → If you train a neural network today and again tomorrow, you want to get the same results (for debugging, research papers, testing).

* But deep learning has many random processes:

1. Random weight initialization

2. Random shuffling of data in DataLoader

3. Random augmentations in images

4. Random GPU operations

So, by **setting the same seed**, we try to make experiments reproducible.

In [114]:
# 🛠 How to set seeds in PyTorch for reproducibility

import torch
import numpy as np
import random

# 1. Set Python’s built-in random seed
random.seed(42)

# 2. Set NumPy’s random seed
np.random.seed(42)

# 3. Set PyTorch seeds (CPU + CUDA)
torch.manual_seed(42)
torch.cuda.manual_seed(42)
torch.cuda.manual_seed_all(42)  # if you’re using multi-GPU

# 4. Make sure deterministic behavior is enabled
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

## ⚠️ Important Note

* Even after setting all seeds:

* **Complete reproducibility** is sometimes **not guaranteed** on GPU because of parallelism and non-deterministic CUDA operations.

* PyTorch warns that this can slow down training (`deterministic=True` makes things strict).

* For **research**, use seeds for fair comparison.

* For **production**, speed may matter more, so you might not always fix seeds.

✅ Summary:

* A seed controls random number generation.

* Reproducibility = getting the same results when running the same code multiple times.

* In PyTorch, set seeds for Python, NumPy, and Torch, and also configure CuDNN.

* Even then, exact reproducibility on GPU may not always be perfect, but it’s usually close enough.

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update the random numbers to try and make them better representation of the data -> again -> again -> again...`

To reduce the randomness in Neural Networks and PyTorch, comes the concept of a **Random Seed**.

Essentially what the random seed does is "flavour" the randomness.

In [115]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
# print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [116]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42 # different flavour of Randomness by using different numbers
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for Reproducibility

* https://docs.pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed

# Different ways of accessing a GPU in PyTorch

## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everthing good.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there’s lots of options..., see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [117]:
!nvidia-smi

Sun Sep 28 19:39:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

The `Tesla T4` is **a professional graphics card by NVIDIA**

### 2. Check for GPU access with PyTorch

In [119]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

🔍 `torch.cuda.is_available()`

This line simply **checks if your computer has a GPU that PyTorch can use.**

* `cuda` = NVIDIA’s GPU computing platform (used to speed up deep learning).

* If PyTorch detects a compatible GPU + CUDA installed properly → it returns **True.**

* Otherwise → it returns **False.**

`torch.cuda.is_available()` checks if your GPU is ready for PyTorch training.

In [120]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

**Abstracted Hardware Access**: For machine learning, this involves writing code that can automatically detect and use available hardware accelerators (like GPUs) without hardcoding the specific hardware, as shown in https://docs.pytorch.org/xla/release/1.12/index.html examples.

In [121]:
# Count number of devices
torch.cuda.device_count()

1

For PyTorch, since it's capable of running compute on GPUs or CPUs, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

E.g. Run on GPU if available, else default to CPU